# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrate"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "main"
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    call_reusable_workflow_integrate:
        uses: "szepeviktor/bladestan/.github/workflows/reusable-integrate.yml@ci-viktor-utopia"
    call_reusable_workflow_spelling:
        uses: "szepeviktor/bladestan/.github/workflows/reusable-spelling.yml@ci-viktor-utopia"
